version = 0.1

[default.deploy.parameters]
stack_name = "email-notifier-stack"
resolve_s3 = true
s3_prefix = "email-notifier-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" FromEmail=\"bousilmustapha@gmail.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
